import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    "en_US" : {
      "yes" : "Yes",
      "no" : "No",
      "notice" : "Notice",
      "english" : "English",
      "vietnamese" : "Vietnamese",
      "theme" : "Theme",
      "sign_in" : "Sign In",
      "sign_up" : "Sign Up",
      "sign_out" : "Sign Out",
      "hello" : "Hello",
      "favorites" : "Favorites",
      "instructions" : "Instructions",
      "mini_game" : "Mini game",
      "changeLanguage" : "Change Language",
      "what_you_want_to_cook_today" : "What do you want to cook today ?",
      "recommended_for_you" : "Recommended for you",
      "delete_account": "Delete account",
      "ask_for_delete" : "You definitely want to delete your account!",
      "random_food_joke" : "Random food joke",
      "sign_in_to_your_account" : "Sign in to your account",
      "health_point" : "Health point",
      "manufacturer_s_review" : "Manufacturer's review",
      "cooking_minutes" : "Cooking minutes",
      "can_not_open_favorite_list" : "Can't open your favorites list!",
      "have_not_login_or_account" : "You haven't logged in or don't have an account yet!",
      "login_or_create_account" : "Log in or create an account to save your favorite recipes!",
      "serving" : "Serving",
    },
    "vi_VN" : {
      "yes" : "Có",
      "no" : "Không",
      "notice" : "Thông báo",
      "english" : "Tiếng Anh",
      "vietnamese" : "Tiếng Việt",
      "theme" : "Chủ đề",
      "sign_in" : "Đăng Nhập",
      "sign_up" : "Đăng Ký",
      "sign_out" : "Đăng Xuất",
      "hello" : "Xin chào",
      "favorites" : "Yêu thích",
      "instructions" : "Hướng dẫn",
      "mini_game" : "Trò chơi nhỏ",
      "changeLanguage" : "Thay đổi ngôn ngữ",
      "what_you_want_to_cook_today" : "Hôm nay bạn muốn nấu món gì ?",
      "recommended_for_you" : "Đề xuất cho bạn",
      "delete_account" : "Xóa tài khoản",
      "ask_for_delete" : "Bạn chắc chắc muốn xóa tài khoản!",
      "random_food_joke" : "Câu đùa ngầu nhiên về đồ ăn",
      "sign_in_to_your_account" : "Đăng nhập vào tài khoản của bạn",
      "health_point" : "Điểm sức khỏe",
      "manufacturer_s_review" : "Đánh giá của nhà sản xuất",
      "cooking_minutes" : "Thời gian nấu",
      "can_not_open_favorite_list" : "Không thể mở danh sách yêu thích của bạn!",
      "have_not_login_or_account" : "Bạn chưa đăng nhặp hoặc chưa có tài khoản!",
      "login_or_create_account" : "Hãy đăng nhập hoặc tạo tài khoản để lưu lại công thức yêu thích!",
      "serving" : "Số người ăn"
    },
  };
}